#!/usr/bin/env dart
// ignore_for_file: avoid_print

/// Switches dependencies between local paths and git URLs.
///
/// Usage:
///   dart scripts/switch_dependencies.dart local   # Create pubspec_overrides.yaml with local paths
///   dart scripts/switch_dependencies.dart remote  # Remove pubspec_overrides.yaml (use git deps from pubspec.yaml)
///
/// Strategy:
/// - pubspec.yaml always contains REMOTE (git) dependencies (committed to repo)
/// - pubspec_overrides.yaml contains LOCAL path dependencies (gitignored)
/// - "local" mode creates the overrides file
/// - "remote" mode deletes the overrides file
///
/// Configuration is defined in scripts/dependencies.yaml

import 'dart:io';

import 'package:yaml/yaml.dart';

/// Dependency configuration for local overrides
class DependencyConfig {
  final String package;
  final String localPath;

  DependencyConfig({
    required this.package,
    required this.localPath,
  });

  factory DependencyConfig.fromYaml(Map<dynamic, dynamic> yaml) {
    return DependencyConfig(
      package: yaml['package'] as String,
      localPath: yaml['local_path'] as String,
    );
  }
}

/// Target pubspec file configuration
class PubspecTarget {
  final String path;
  final List<String> dependencies;

  PubspecTarget({
    required this.path,
    required this.dependencies,
  });

  factory PubspecTarget.fromYaml(Map<dynamic, dynamic> yaml) {
    return PubspecTarget(
      path: yaml['path'] as String,
      dependencies: (yaml['dependencies'] as List<dynamic>).cast<String>(),
    );
  }

  /// Get the overrides file path for this pubspec
  String get overridesPath {
    final String dir = path.substring(0, path.lastIndexOf('/') + 1);
    return '${dir}pubspec_overrides.yaml';
  }
}

void main(List<String> args) {
  if (args.isEmpty || !['local', 'remote'].contains(args[0])) {
    print('Usage: dart scripts/switch_dependencies.dart <local|remote>');
    print('');
    print('  local   - Create pubspec_overrides.yaml with local path dependencies');
    print('  remote  - Remove pubspec_overrides.yaml (use git deps from pubspec.yaml)');
    exit(1);
  }

  final String mode = args[0];
  final bool useLocal = mode == 'local';

  // Find the root directory (where this script lives)
  final String scriptPath = Platform.script.toFilePath();
  final Directory scriptDir = File(scriptPath).parent;
  final Directory rootDir = scriptDir.parent;

  // Load configuration
  final File configFile = File('${scriptDir.path}/dependencies.yaml');
  if (!configFile.existsSync()) {
    print('Error: Configuration file not found: ${configFile.path}');
    exit(1);
  }

  final String configContent = configFile.readAsStringSync();
  final YamlMap config = loadYaml(configContent) as YamlMap;

  // Parse dependency configurations
  final List<DependencyConfig> dependencies = (config['dependencies'] as YamlList)
      .map((dynamic e) => DependencyConfig.fromYaml(e as Map<dynamic, dynamic>))
      .toList();

  // Parse pubspec targets
  final List<PubspecTarget> targets = (config['pubspec_files'] as YamlList)
      .map((dynamic e) => PubspecTarget.fromYaml(e as Map<dynamic, dynamic>))
      .toList();

  // Create a map for quick lookup
  final Map<String, DependencyConfig> depMap = {
    for (final DependencyConfig dep in dependencies) dep.package: dep,
  };

  print('Switching dependencies to ${useLocal ? "LOCAL" : "REMOTE"} mode...');
  print('');

  // Process each pubspec file
  for (final PubspecTarget target in targets) {
    final String overridesPath = '${rootDir.path}/${target.overridesPath}';
    final File overridesFile = File(overridesPath);

    print('Processing: ${target.path}');

    if (useLocal) {
      // Create pubspec_overrides.yaml with local dependencies
      final StringBuffer buffer = StringBuffer();
      buffer.writeln('# Auto-generated by switch_dependencies.dart');
      buffer.writeln('# This file is gitignored - do not commit');
      buffer.writeln('dependency_overrides:');

      for (final String depName in target.dependencies) {
        final DependencyConfig? dep = depMap[depName];
        if (dep == null) {
          print('  Warning: Dependency config not found for: $depName');
          continue;
        }
        buffer.writeln('  $depName:');
        buffer.writeln('    path: ${dep.localPath}');
        print('  + $depName: ${dep.localPath}');
      }

      overridesFile.writeAsStringSync(buffer.toString());
      print('  -> Created ${target.overridesPath}');
    } else {
      // Remove pubspec_overrides.yaml to use git dependencies from pubspec.yaml
      if (overridesFile.existsSync()) {
        overridesFile.deleteSync();
        print('  -> Deleted ${target.overridesPath}');
      } else {
        print('  -> ${target.overridesPath} not found (already using remote)');
      }
    }
    print('');
  }

  print('Done! Dependencies switched to ${useLocal ? "LOCAL" : "REMOTE"} mode.');
  if (useLocal) {
    print('');
    print('Note: pubspec_overrides.yaml files are gitignored.');
    print('Run "dart scripts/switch_dependencies.dart remote" before committing.');
  }
}
